[package]
name = "allow_threads"
version = "0.1.0"
edition = "2021"

[lib]
name = "allow_threads"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.15", features = ["extension-module"] }

[build-dependencies]
pyo3-build-config = "0.15"

